export const buyerLeadsData = [
  {
    id: "RFQ ID: 1R0002FDI",
    state: "Lagos",
    category: "Crop Products",
    name: "Cocoa Beans",
    quantity: "30MT",
    specs: "8% Moisture content dried half of a yellow",
    time: "10 hour(s) before",
    key: "12wq",
  },

  {
    id: "RFQ ID: 1R0002FDI",
    state: "Lagos",
    category: "Crop Products",
    name: "Cocoa Beans",
    quantity: "30MT",
    specs: "8% Moisture content dried halfa sdadad",
    time: "10 hour(s) before",
    key: "12wq1",
  },
  {
    id: "RFQ ID: 1R0002FDI",
    state: "Lagos",
    category: "Crop Products",
    name: "Cocoa Beans",
    quantity: "30MT",
    specs: "8% Moisture content dried halfa sdadad",
    time: "10 hour(s) before",
    key: "12wq2",
  },
  {
    id: "RFQ ID: 1R0002FDI",
    state: "Lagos",
    category: "Crop Products",
    name: "Cocoa Beans",
    quantity: "30MT",
    specs: "8% Moisture content dried halfa sdadad",
    time: "10 hour(s) before",
    key: "12wq3",
  },
  {
    id: "RFQ ID: 1R0002FDI",
    state: "Lagos",
    category: "Crop Products",
    name: "Cocoa Beans",
    quantity: "30MT",
    specs: "8% Moisture content dried halfa sdadad",
    time: "10 hour(s) before",
    key: "12wq4",
  },
  {
    id: "RFQ ID: 1R0002FDI",
    state: "Lagos",
    category: "Crop Products",
    name: "Cocoa Beans",
    quantity: "30MT",
    specs: "8% Moisture content dried halfa sdadad",
    time: "10 hour(s) before",
    key: "12wq5",
  },
  {
    id: "RFQ ID: 1R0002FDI",
    state: "Lagos",
    category: "Crop Products",
    name: "Cocoa Beans",
    quantity: "30MT",
    specs: "8% Moisture content dried halfa sdadad",
    time: "10 hour(s) before",
    key: "12wq6",
  },
  {
    id: "RFQ ID: 1R0002FDI",
    state: "Lagos",
    category: "Crop Products",
    name: "Cocoa Beans",
    quantity: "30MT",
    specs: "8% Moisture content dried halfa sdadad",
    time: "10 hour(s) before",
    key: "12wq7",
  },
];
