export const productsTableData = {
  column: ["Name", "Price", "Quantity", "Status", "Clicks", "Date Uploaded"],
  data: [
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "asxvvxsaas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "ass121aas",
    },
    {
      Name: "Cocoa",
      Price: "N150/Kg",
      Quantity: "30,000 kg",
      Status: "Active",
      Clicks: "10 Clicks",
      "Date Uploaded": "10/12/2022",
      key: "assaasas",
    },
  ],
};
